# Generated by Django 2.0.13 on 2020-07-27 22:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0011_auto_20200727_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='farms.Farm', verbose_name='Farm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(verbose_name='Type')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledgers.Ledger', verbose_name='Ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
