# Generated by Django 2.0.13 on 2020-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'verbose_name': 'Ledger', 'verbose_name_plural': 'Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='ledgerentries',
            options={'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AddField(
            model_name='ledger',
            name='contact_number',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Contact number'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='location',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='ledgerentries',
            name='type',
            field=models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')], verbose_name='Type'),
        ),
    ]
