# Generated by Django 2.0.13 on 2020-07-27 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_auto_20200727_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentries',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 27, 23, 24, 40, 427175, tzinfo=utc), verbose_name='Transaction date'),
        ),
    ]
