# Generated by Django 2.0.13 on 2020-07-27 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_ledgerentries_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentries',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Transaction date'),
        ),
    ]
