# Generated by Django 3.0.8 on 2020-07-25 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(choices=[(1, 'Summer'), (2, 'Winter'), (3, 'Mid season')], max_length=550, verbose_name='Season')),
                ('breed', models.CharField(max_length=550, verbose_name='breed')),
                ('total_acres', models.FloatField(verbose_name='Total acres')),
                ('date_sowing', models.DateField(verbose_name='Date sowing')),
                ('date_harvesting', models.DateField(blank=True, verbose_name='Date harvesting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Crop Name')),
                ('description', models.CharField(blank=True, max_length=550, null=True, verbose_name='Description')),
            ],
            options={
                'permissions': (('can_view_crop', 'Can View Crop'),),
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Farm Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'permissions': (('can_view_farm', 'Can View Farm'),),
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('total_mann', models.FloatField(help_text='Total mann weight', verbose_name='Total mann')),
                ('rate_per_mann', models.IntegerField(help_text='Per mann rate', verbose_name='Rate per mann')),
                ('sold_date', models.DateField(verbose_name='Sold date')),
                ('notes', models.CharField(blank=True, max_length=550, null=True, verbose_name='Notes')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Crop', verbose_name='Crop')),
            ],
            options={
                'ordering': ('-sold_date',),
                'permissions': (('can_view_output', 'Can View Output'),),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Field Name')),
                ('location', models.CharField(blank=True, max_length=550, verbose_name='Location')),
                ('is_own_property', models.BooleanField(verbose_name='Is Own Property')),
                ('has_electricity_tubewell', models.BooleanField(verbose_name='Has Electricity tubewell')),
                ('has_canal_irrigation', models.BooleanField(verbose_name='Has Canal Irrigation')),
                ('total_acres', models.FloatField(verbose_name='Total Acres')),
                ('landlord_name', models.CharField(blank=True, help_text='Landlord name if not owned', max_length=550, verbose_name='Landlord Name')),
                ('landlord_number', models.CharField(blank=True, help_text='Landlord number if not owned', max_length=550, verbose_name='Landlord Number')),
                ('lease_per_acre', models.FloatField(blank=True, help_text='If leased then theka in thousands', verbose_name='Lease per acre')),
                ('lease_start', models.DateField(blank=True, help_text='Lease start date if not owned', verbose_name='Lease start')),
                ('lease_end', models.DateField(blank=True, help_text='Lease end date if not owned', verbose_name='Lease end')),
                ('is_active', models.BooleanField(default=True, help_text='Is lease active', verbose_name='Is Active')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Farm', verbose_name='Farm')),
            ],
            options={
                'permissions': (('can_view_khoohORField', 'Can View KhoohORField'),),
            },
        ),
        migrations.CreateModel(
            name='FarmAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Asset Name')),
                ('date_purchased', models.DateField(verbose_name='Date purchased')),
                ('is_bought_new', models.BooleanField(verbose_name='Is purchased new')),
                ('purchase_cost', models.IntegerField(help_text='Amount in rupees', verbose_name='Purchase cost')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Farm', verbose_name='Farm')),
            ],
            options={
                'permissions': (('can_view_farmAsset', 'Can View FarmAsset'),),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[(1, 'Seed'), (2, 'Fertilizer'), (3, 'Pesticides'), (4, 'Water'), (5, 'Electricity_bill'), (6, 'Oil'), (7, 'Labour'), (8, 'Miscellaneous')], max_length=255, verbose_name='Expense type')),
                ('expense_date', models.DateField(verbose_name='Expense date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('notes', models.TextField(null=True, verbose_name='Notes')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_expenditures', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Crop', verbose_name='Crop')),
                ('expend_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to=settings.AUTH_USER_MODEL, verbose_name='Expend by')),
            ],
            options={
                'ordering': ('-expense_date',),
                'permissions': (('can_view_expense', 'Can View Expense'),),
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.CropType', verbose_name='Crop type'),
        ),
        migrations.AddField(
            model_name='crop',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Field', verbose_name='Field'),
        ),
    ]
