# Generated by Django 3.0.8 on 2020-07-24 20:46

import apps.farms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name_urdu', models.CharField(max_length=500, verbose_name='فصل کا نام')),
                ('name', models.CharField(max_length=550, verbose_name='Crop Name')),
            ],
            options={
                'permissions': (('can_view_crop', 'Can View Crop'),),
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name_urdu', models.CharField(max_length=500, verbose_name='فارم ہاؤس کا نام')),
                ('name', models.CharField(max_length=550, verbose_name='Farm Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_farm', 'Can View Farm'),),
            },
        ),
        migrations.CreateModel(
            name='Fasal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(choices=[('summer', 'SUMMER'), ('winter', 'WINTER'), ('mid_season', 'MID_SEASON')], max_length=550)),
                ('total_acres', models.FloatField()),
                ('date_sowing', models.DateField()),
                ('date_harvesting', models.DateField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Crop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('total_mann', models.FloatField(help_text='Total mann weight')),
                ('rate_per_mann', models.IntegerField(help_text='Per mann rate')),
                ('sold_date', models.DateField()),
                ('fasal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Fasal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhoohORField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name_urdu', models.CharField(max_length=550, verbose_name='فارم ہاؤس کا نام')),
                ('location', models.CharField(blank=True, max_length=550)),
                ('is_own_property', models.BooleanField()),
                ('has_electricity_tubewell', models.BooleanField()),
                ('has_canal_irrigation', models.BooleanField()),
                ('total_acres', models.FloatField()),
                ('zameendaar_name', models.CharField(blank=True, help_text='Zameendaar name if not owned', max_length=550)),
                ('zameendaar_number', models.CharField(blank=True, help_text='Zameendaar number if not owned', max_length=550)),
                ('per_acre_theka', models.FloatField(blank=True, verbose_name='If leased then theka in thousands')),
                ('lease_start', models.DateField(blank=True)),
                ('lease_end', models.DateField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Farm')),
            ],
            options={
                'permissions': (('can_view_khoohORField', 'Can View KhoohORField'),),
            },
        ),
        migrations.AddField(
            model_name='fasal',
            name='khooh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.KhoohORField'),
        ),
        migrations.CreateModel(
            name='FarmAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name_urdu', models.CharField(max_length=500, verbose_name='اوزار کا نام')),
                ('name', models.CharField(max_length=550, verbose_name='Asset Name')),
                ('date_purchased', models.DateTimeField()),
                ('is_bought_new', models.BooleanField()),
                ('purchase_cost', models.IntegerField(help_text='Amount in thousands rupees')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Farm')),
            ],
            options={
                'permissions': (('can_view_farmAsset', 'Can View FarmAsset'),),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('seed', 'SEED'), ('fertilizer', 'FERTILIZER'), ('pesticides', 'PESTICIDES'), ('water', 'WATER'), ('electricity_bill', 'ELECTRICITY_BILL'), ('oil', 'OIL'), ('labour', 'LABOUR'), ('miscellaneous', 'MISC'), (apps.farms.models.ExpenseType.Meta, 'Meta')], max_length=255)),
                ('expense_date', models.DateField()),
                ('amount', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_expenditures', to=settings.AUTH_USER_MODEL)),
                ('expend_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to=settings.AUTH_USER_MODEL)),
                ('fasal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.Fasal')),
            ],
            options={
                'ordering': ('-expense_date',),
                'permissions': (('can_view_expense', 'Can View Expense'),),
            },
        ),
    ]
