# Generated by Django 3.0.8 on 2020-07-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('1', 'Summer'), ('2', 'Winter'), ('3', 'Mid season')], max_length=550, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_expenses', to='farms.Crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('1', 'Seed'), ('2', 'Fertilizer'), ('3', 'Pesticides'), ('4', 'Water'), ('5', 'Electricity_bill'), ('6', 'Oil'), ('7', 'Labour'), ('8', 'Miscellaneous')], max_length=255, verbose_name='Expense type'),
        ),
        migrations.AlterField(
            model_name='output',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_outputs', to='farms.Crop', verbose_name='Crop'),
        ),
    ]
