# Generated by Django 3.0.8 on 2020-07-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_auto_20200725_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'permissions': (('can_view_crop', 'Can View Crop'),), 'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='croptype',
            options={'permissions': (('can_view_crop', 'Can View Crop'),), 'verbose_name': 'Crop type', 'verbose_name_plural': 'Crop types'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-expense_date',), 'permissions': (('can_view_expense', 'Can View Expense'),), 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='farmasset',
            options={'permissions': (('can_view_farmAsset', 'Can View FarmAsset'),), 'verbose_name': 'Farm Asset', 'verbose_name_plural': 'Farm Assets'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'permissions': (('can_view_field', 'Can View Field'),), 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ('-sold_date',), 'permissions': (('can_view_output', 'Can View Output'),), 'verbose_name': 'Output', 'verbose_name_plural': 'Outputs'},
        ),
    ]
