# Generated by Django 3.0.8 on 2020-07-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20200725_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='description_en',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='description_ur',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='name_en',
            field=models.CharField(max_length=550, null=True, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='name_ur',
            field=models.CharField(max_length=550, null=True, verbose_name='Crop Name'),
        ),
    ]
