# Generated by Django 3.0.8 on 2020-07-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_auto_20200725_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expend_by',
            new_name='spent_by',
        ),
    ]
