# Generated by Django 3.0.8 on 2020-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_auto_20200726_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='date_harvesting',
            field=models.DateField(blank=True, null=True, verbose_name='Date harvesting'),
        ),
    ]
