# Generated by Django 2.0.13 on 2020-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_auto_20200726_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='lease_end',
            field=models.DateField(blank=True, help_text='Lease end date if not owned', null=True, verbose_name='Lease end'),
        ),
        migrations.AlterField(
            model_name='field',
            name='lease_per_acre',
            field=models.FloatField(blank=True, help_text='If leased then theka in thousands', null=True, verbose_name='Lease per acre'),
        ),
        migrations.AlterField(
            model_name='field',
            name='lease_start',
            field=models.DateField(blank=True, help_text='Lease start date if not owned', null=True, verbose_name='Lease start'),
        ),
    ]
