# Generated by Django 2.0.13 on 2020-07-27 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_auto_20200727_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='rate_per_mann',
            field=models.IntegerField(help_text='Per mann rate', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rate per mann'),
        ),
        migrations.AlterField(
            model_name='output',
            name='total_mann',
            field=models.FloatField(help_text='Total mann weight', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Total mann'),
        ),
    ]
